### PR TITLE
Add ES6 ESLint rules

### PR DESCRIPTION
**Pull request by limonte**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/eslint-config-vaadin/4)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[index.js, line 267 at r1](https://reviewable.io:443/reviews/vaadin/eslint-config-vaadin/4#-Kd5hzZtYMhJkJr1L3la:-Kd5hzZtYMhJkJr1L3lb:b-6qsvek) ([raw file](https://github.com/vaadin/eslint-config-vaadin/blob/d1917da4902e47c67878cb944128e53ac705118e/index.js#L267)):*
> ```JavaScript
>     'no-useless-constructor': 2,
>     'no-useless-rename': 2,
>     // 'no-var': 0,
> ```

I would disallow `var` to require using `let` and `const` everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eslint-config-vaadin/4)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[index.js, line 267 at r1](https://reviewable.io:443/reviews/vaadin/eslint-config-vaadin/4#-Kd5hzZtYMhJkJr1L3la:-Kd5jHN9IqezdGqKCq5D:b-6zyluk) ([raw file](https://github.com/vaadin/eslint-config-vaadin/blob/d1917da4902e47c67878cb944128e53ac705118e/index.js#L267)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

I would disallow `var` to require using `let` and `const` everywhere.
</blockquote></details>

I also thought about forcing using `let` and `const` but for now we need to keep the compatibility of this config and our pre-ES6 components. In case of turning this rule on, we'll need to disable it for grid/date-picker/etc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eslint-config-vaadin/4)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eslint-config-vaadin/4#-:-Kd5sDV3XuXFF9AVAI0z:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/eslint-config-vaadin/4#-:-KdGdm4DyMe3ttgs1k2h:bnfp4nl)*

**Pull request merged**
